projectName: todos

collections:
    todos:
        fields:
            todo:
                type: varchar
                required: true
            done:
                type: bool

        routes:
            get: true
            get-single: false
            post: true
            put: true
            delete: false
